source 'https://github.com/CocoaPods/Specs.git'

target 'SocialInvite', :exclusive => true do
  pod "SocialInvite", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SocialInvite", :path => "../"

  
end
